### ISSUE TITLE
RuntimeError: Save not found????

### ISSUE THREAD

**Issue by samm29299** [Dylan-Zheng/Rise-of-Kingdoms-Bot#101]
hay 
i need help here plz

when i mark on attack barbarians
the bot don't attack he go back to city

and this the code show to me

 Traceback (most recent call last):
  File "tasks\Barbarians.py", line 87, in do
  File "tasks\Barbarians.py", line 256, in select_save_blue_one
RuntimeError: Save not found
libpng warning: iCCP: known incorrect sRGB profile 

what i do any one can help me :(

**Comment by samm29299** [comment]
File "tasks\Barbarians.py", line 256, in select_save_blue_one
what is the blue mean ?

**Comment by yuceltoluyag** [comment]
> File "tasks\Barbarians.py", line 256, in select_save_blue_one what is the blue mean ?

You can watch my video for installation. The answer to the second question is that you must create ready-made military units. This is how you attack the barbarians, ot
herwise you will get an error. . This is what it looks like when you create it.

https://youtu.be/6IObh_HJvrk

![bb](https://user-images.githubusercontent.com/16064131/164987633-0270be01-9883-422d-a18d-b8442085cff0.jpg)

**Comment by silverwolfceh** [comment]
I already have it but still runtime error
