### ISSUE TITLE
ERROR_TOO_BIG_CAPTCHA_FILESIZE

### ISSUE THREAD

**Issue by JuniorDeveloperUA** [Dylan-Zheng/Rise-of-Kingdoms-Bot#104]
Traceback (most recent call last):
  File "tasks\Task.py", line 172, in pass_verification
  File "bot_related\twocaptcha.py", line 68, in solve_verification
  File "bot_related\twocaptcha.py", line 44, in send_base64_image
RuntimeError: 2Captcha Error: ERROR_TOO_BIG_CAPTCHA_FILESIZE

pls i need you :D

**Comment by JuniorDeveloperUA** [comment]
i fix it by changing image(captcha) size, and new coordinates to tap and now captcha working fine) 
if you want i can put working project on git, or write here what to change

sry for my bad english)

**Comment by TuanVN008** [comment]
5$ pls

**Comment by JuniorDeveloperUA** [comment]
> 5$ pls

i fix it

**Comment by josef300** [comment]
> > 5$ pls
> 
> i fix it

how? can u tell me pls

**Comment by TuanVN008** [comment]
> > > 5$ pls
> 
> > 
> 
> > i fix it
> 
> 
> 
> how? can u tell me pls

U have discord?

**Comment by TuanVN008** [comment]
Inbox me. Discord : LG Electric#0239

**Comment by JuniorDeveloperUA** [comment]
> > > 5$ pls
> > 
> > 
> > i fix it
> 
> how? can u tell me pls

https://discord.gg/7BbJY2cxNc join my discord server

**Comment by JuniorDeveloperUA** [comment]
> Inbox me. Discord : LG Electric#0239

https://discord.gg/7BbJY2cxNc
