### ISSUE TITLE
RuntimeError: ERROR: 'FAIL' 000edevice offline

### ISSUE THREAD

**Issue by WiiZiii** [Dylan-Zheng/Rise-of-Kingdoms-Bot#115]
Hello I had this error: 

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "gui\device_list_frame.py", line 128, in callback
  File "gui\selected_device_frame.py", line 23, in __init__
  File "bot_related\bot.py", line 49, in __init__
  File "ppadb\command\transport\__init__.py", line 20, in shell
  File "ppadb\device.py", line 45, in create_connection
  File "ppadb\command\transport\__init__.py", line 15, in transport
  File "ppadb\connection.py", line 84, in send
  File "ppadb\connection.py", line 90, in _check_status
RuntimeError: ERROR: 'FAIL' 000edevice offline

I checked that everything was good in my settings and everything seems to be ok, I restarted the program several times but I still get the same error.
Does anyone have a solution please?

**Comment by Bramerderino** [comment]
I had the same problem and doublechecking my device port and ip on the emulator worked, the port was 5556 instead of 5555 what everyone else has
