### ISSUE TITLE
RuntimeError('Save not found')

### ISSUE THREAD

**Issue by koffein7755** [Dylan-Zheng/Rise-of-Kingdoms-Bot#120]
Please help, bot does not send the commander to barbarians.

Error:

`Traceback (most recent call last):
  File "tasks\Barbarians.py", line 87, in do
    self.select_save_blue_one()
  File "tasks\Barbarians.py", line 256, in select_save_blue_one
    raise RuntimeError('Save not found')
RuntimeError: Save not found`

**Comment by koffein7755** [comment]
figured it out, inattentively watched the video (
