### ISSUE TITLE
RuntimeError: Save not found

### ISSUE THREAD

**Issue by metapodcod** [Dylan-Zheng/Rise-of-Kingdoms-Bot#38]
version https://github.com/Dylan-Zheng/Rise-of-Kingdoms-Bot/releases/tag/v1.4.2.052421_beta
game level : 12
emulator : bluestacks

```
  File "tasks\Materials.py", line 26, in do
KeyError: 'blacksmith'
Traceback (most recent call last):
  File "tasks\Materials.py", line 26, in do
KeyError: 'blacksmith'
Traceback (most recent call last):
  File "tasks\Barbarians.py", line 87, in do
  File "tasks\Barbarians.py", line 256, in select_save_blue_one
RuntimeError: Save not found
Traceback (most recent call last):
  File "tasks\Materials.py", line 26, in do
KeyError: 'blacksmith'
Traceback (most recent call last):
  File "tasks\Barbarians.py", line 87, in do
  File "tasks\Barbarians.py", line 256, in select_save_blue_one
RuntimeError: Save not found
libpng warning: iCCP: known incorrect sRGB profile

```

**Comment by Dylan-Zheng** [comment]
auto attack barbarian will require you to using blue first save.
and make sure screen resolution is 1280 x 720.

**Comment by metapodcod** [comment]
> auto attack barbarian will require you to using blue first save.
> and make sure screen resolution is 1280 x 720.

thank you, can you add auto-join to rallies?

**Comment by metapodcod** [comment]
lately, i've been encountering the error frequently  @Dylan-Zheng 
```
Traceback (most recent call last):
  File "bot_related\device_gui_detector.py", line 177, in barbarians_level_image_to_string
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "bot_related\device_gui_detector.py", line 177, in barbarians_level_image_to_string
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "tasks\Barbarians.py", line 58, in do
TypeError: cannot unpack non-iterable NoneType object
```
