### ISSUE TITLE
display error?

### ISSUE THREAD

**Issue by fredothevirgin1** [Dylan-Zheng/Rise-of-Kingdoms-Bot#44]
when trying to display on the rok bot.exe (v1.4.3.060721_beta) the program stops responding and I get this error:  ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

**Comment by CaptainMcFilthy** [comment]
how do i get the bot to even show up i have it connected but nothing else happens

**Comment by CaptainMcFilthy** [comment]
it says its connected but when i press display it says: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "gui\device_list_frame.py", line 128, in callback
  File "gui\selected_device_frame.py", line 23, in __init__
  File "bot_related\bot.py", line 49, in __init__
  File "ppadb\command\transport\__init__.py", line 20, in shell
  File "ppadb\device.py", line 45, in create_connection
  File "ppadb\command\transport\__init__.py", line 15, in transport
  File "ppadb\connection.py", line 84, in send
  File "ppadb\connection.py", line 90, in _check_status
RuntimeError: ERROR: 'FAIL' 000edevice offline

how do i fix this

**Comment by kunalkapoor** [comment]
Just delete and re-add your emulator instance and it'll work. Not sure what caused this, but this workaround fixed it.
