### ISSUE TITLE
please dylan

### ISSUE THREAD

**Issue by RevengeSTK** [Dylan-Zheng/Rise-of-Kingdoms-Bot#71]
please, this bot is so good and we need it back :(

**Comment by ibra5757** [comment]
Traceback (most recent call last):
  File "adb.py", line 30, in get_device
  File "adb.py", line 20, in connect_to_device
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 490, in run
  File "subprocess.py", line 964, in communicate
  File "subprocess.py", line 1298, in _communicate
subprocess.TimeoutExpired: Command '['C:\\Users\\Hooria Ibrahim\\Desktop\\Rise Of Kingdom Bot v1.4.3.060721_beta\\adb\\adb.exe', 'connect', '192.168.67.119:12000']' timed out after 2 seconds
