### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by SillyeGergo** [Dylan-Zheng/Rise-of-Kingdoms-Bot#89]
When I start the bot, i get this message: 

Traceback (most recent call last):
  File "F:\Programs\Rise-of-Kingdoms-Bot-main\gui\creator.py", line 144, in load_bot_config
    with open(resource_path(FilePaths.SAVE_FOLDER_PATH.value + '{}_config.json'.format(prefix))) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Programs\\Rise-of-Kingdoms-Bot-main\\save\\127.0.0.1_5555_config.json'
Traceback (most recent call last):
  File "F:\Programs\Rise-of-Kingdoms-Bot-main\gui\creator.py", line 161, in load_building_pos
    with open(resource_path(FilePaths.SAVE_FOLDER_PATH.value + "{}_building_pos.json".format(prefix)
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Programs\\Rise-of-Kingdoms-Bot-main\\save\\127.0.0.1_5555_building_pos.json'

The game wants to quit every 3 seconds

**Comment by frogedr** [comment]
Same issue too can we get some help?

**Comment by YorickLB** [comment]
Just create a folder called save and done then it should work

**Comment by alpeerkaraca** [comment]
Enter whereever your bot files are saved then create a folder named "save". After creating folder enter the folder and create two files with thoose names:

'127.0.0.1_5555_building_pos.json' //Requires for saving location of your buildings.
'127.0.0.1_5555_config.json' //Requires for saving configurations you made. @frogedr @SillyeGergo
